# build stage
FROM daocloud.io/library/node
WORKDIR /app
COPY package*.json ./
RUN npm install --registry=https://registry.npm.taobao.org
COPY . .
RUN npm run docs:build

# production stage
FROM daocloud.io/library/nginx:1.13.0-alpine
COPY  /app/nginx.conf /etc/nginx/nginx.conf
COPY  /app/docs/.vuepress/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
