FROM daocloud.io/library/node as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run docs:build

FROM daocloud.io/library/nginx:1.13.0-alpine
COPY  --from=build-stage  /app/nginx.conf /etc/nginx/nginx.conf
COPY  --from=build-stage  /app/dist/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
