# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: 上传docker镜像
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: hyh_backend/my_blog
          tags: latest
          registry: ccr.ccs.tencentyun.com
          dockerfile: Dockerfile.yml
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PWD }}
      - name: 更新docker文件
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.ServerUserName }}
          password: ${{ secrets.ServerPWD }}
          port: ${{ secrets.PORT }}
          script: docker rm -f blog && docker pull ccr.ccs.tencentyun.com/hyh_backend/my_blog:latest && docker run -d --rm -p 80:80 --name blog ccr.ccs.tencentyun.com/hyh_backend/my_blog:latest
